name: Update Latest Projects

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly update
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install PyGithub
      - name: Update README
        run: python .github/scripts/update_projects.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull latest changes
  run: |
    git config user.name "${{ github.actor }}"
    git config user.email "${{ github.actor }}@users.noreply.github.com"
    git pull origin main
    
      - name: Push changes
 run:  |
    git push origin main
